"use client"

import "./globals.css";
import { Inter } from "next/font/google";
import ThemeProvider from "@mui/material/styles/ThemeProvider";
import createTheme from "@mui/material/styles/createTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const themeOptions = {
  palette: {
    type: "dark",
    primary: {
      main: "#2874d4",
      dark: "#60c3ef",
    },
    secondary: {
      main: "#24d068",
    },
    info: {
      main: "#2182ce",
    },
  },
};

let theme = createTheme(themeOptions);


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
